### ISSUE TITLE
登録されているイベントがカレンダーに表示されていない

### ISSUE THREAD

**Issue by ChanyaVRC** [kaikoga/Vche#80]
# description
11/27(土) 開催のイベント「[Cafe Q](https://vche.jp/events/bfb965a0)」がイベントに表示されるが、カレンダーに表示されていない。
![image](https://user-images.githubusercontent.com/63221603/143677264-acd07e76-7ddd-48c0-8ac3-b9c9559ff707.png)
![image](https://user-images.githubusercontent.com/63221603/143677243-8b102769-e1a7-4a8a-aae3-5fdd758562a5.png)

# solution 
登録されている全てのイベントがカレンダーに表示され、正しい日時で参照できるようにする。

**Comment by kaikoga** [comment]
## 仕様？不具合？

実はトップページのカレンダーに表示されるイベントは AI によって選ばれており、現在は「主催が存在する `公開` のイベント」という条件になっています。
「Cafe Q」 は主催が存在していない（参加者によって入力された）イベントであり、この条件から外れるため、トップのカレンダーに表示されていません。

・・・さて、これが仕様なのか不具合なのかは難しい質問です。
理想的には、Vcheにイベントを登録するイベント運営が50人くらいいて、一般参加者が200人くらいいて、「主催が存在する `公開` のイベント」という条件だけでトップページのカレンダーが埋まるという状態が想定されます。
このような状態では悪意を持ったユーザーがインチキ情報を入力する可能性があるため、それをある程度抑制する仕組みとして、現状では「主催が存在する」という隠し条件が入っています。
イベントに主催が存在するためには、主催者本人がイベント情報を入力する必要があります。
（主催者を名乗りつつインチキ情報を入力する人が現れることも想定されますが、イベント情報の入力にはTwitterログインが必要なのでその可能性は薄いでしょう）

一方で、現実的には今のところはそこまで流行っていないので、現状ではそれは杞憂です。
実際、ヘルプには「 `公開` に設定していればトップページのカレンダーに表示されます」と書かれているので、現状の挙動は嘘をついています。
なので、 `公開` に設定されている一般参加者のタレコミをトップページのカレンダーに表示するのは、正しい挙動かもしれません。

ここで、「全てのイベントが一般参加者によってタレコまれることを望んでいるのか」ということにも留意しなければなりません。
例えば、内輪のイベントや、イベントの雰囲気を維持するために積極的にVRCイベントカレンダーに載せていないようなイベントを、一般参加者がトップページのカレンダーに乗せることが技術的には可能です。
それがVRSNSのイベント文化に影響を与えてしまう恐れが否定できないので、そのような機能は（本サービスの影響力を鑑みながら）慎重に実装すべきという見方があります。

もちろん、本サービスが今後そのような使い方を望まれるかもしれません。
十分にイベントの件数が多ければ、トップページに全ての `公開` イベントが掲載されることを誰も気にしないかもしれません。

## まともな対応

環境変数などでトップページに表示されるカレンダーのデフォルトの絞り込み条件を切り替えられるようにすべきです。
そのような対応が近いうちに入ると思いますが、同時に [使われ方を監視できるようにする](https://github.com/kaikoga/Vche/issues/36) 必要があるので、そうなると思います。
その上で、当分の間はユーザーの良心を信じて「主催が存在する」の条件を外すことになると思います。

もしかしたら、トップページをはじめとする各所のカレンダー表示にTrust値による絞り込みが追加されるかもしれません。
具体的な実装はあとで考えます。

**Comment by kaikoga** [comment]
https://vche.jp/

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/4142423/144717134-b3a102f1-24e1-4dda-9b76-be5bf9b7320c.png">

Vche 0.3.3 の更新をもちましてトップページのカレンダーに非公式情報が表示されるようになりました。
